// Ticket Radar settings. Generated by the setup page.
window.TR_CONFIG = {
  supabaseUrl: "https://lubhrvhmkaleipijhafc.supabase.co",
  supabaseAnonKey: "sb_publishable_XPPvuai2r8c82dRj_Of-eg_uwMpbez_",
  company: "",
  contactEmail: "",
};
